### PR TITLE
Update Azure devops ENV variables

### PR DESCRIPTION
**Pull request by pvrcs**
Changed the Azure DevOps ENV variables to use capitalized strings and replaced "." with "_".
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#understand-variable-syntax

### CODE REVIEW

**Review by tido64 — APPROVED** [review]
Thanks! Could you please update the tests as well? Weird that the tests didn't trigger on this.

**Comment by pvrcs** [comment]
> Thanks! Could you please update the tests as well? Weird that the tests didn't trigger on this.

Tests were triggered. But I only changed the node ENV variable names, no tests have failed.

**Comment by tido64** [comment]
> I only changed the node ENV variable names, no tests have failed. Probably that's why nothing failed.

Yeah, but those same variables are used in the tests. I guess I didn't check the values so it doesn't trigger anything. Anyway, it's something I can take a look at later.

**Pull request merged**
